version: '3.8'
services:
  gateway:
    build: gateway
    container_name: gateway
    depends_on:
      - server
    ports:
      - "8080:8080"
    environment:
#      - TZ=Asia/Yekaterinburg
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: server
#    image: server
    container_name: server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
#      - TZ=Asia/Yekaterinburg
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - SPRING_DATASOURCE_PASSWORD=shareit
      - SPRING.DATASOURCE.USERNAME=shareit

  db:
    image: postgres:14-alpine
    container_name: db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_PASSWORD=shareit
      - POSTGRES_USER=shareit
      - POSTGRES_DB=shareit
#      - DB_HOST=db
#      - DB_PORT=5432
#      - TZ=Europe/Moscow